// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: work_leave.proto

package work_leave;

public interface EmployeeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:work_leave.Employee)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 employee_id = 1;</code>
   */
  int getEmployeeId();

  /**
   * <code>string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>float accrued_leave_days = 3;</code>
   */
  float getAccruedLeaveDays();

  /**
   * <code>float requested_leave_days = 4;</code>
   */
  float getRequestedLeaveDays();
}
