// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: work_leave.proto

package work_leave;

/**
 * <pre>
 * Message Type definition for LeaveEligibility response.
 * </pre>
 *
 * Protobuf type {@code work_leave.LeaveEligibility}
 */
public  final class LeaveEligibility extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:work_leave.LeaveEligibility)
    LeaveEligibilityOrBuilder {
  // Use LeaveEligibility.newBuilder() to construct.
  private LeaveEligibility(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private LeaveEligibility() {
    eligible_ = false;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private LeaveEligibility(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            eligible_ = input.readBool();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return work_leave.WorkLeaveProto.internal_static_work_leave_LeaveEligibility_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return work_leave.WorkLeaveProto.internal_static_work_leave_LeaveEligibility_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            work_leave.LeaveEligibility.class, work_leave.LeaveEligibility.Builder.class);
  }

  public static final int ELIGIBLE_FIELD_NUMBER = 1;
  private boolean eligible_;
  /**
   * <code>bool eligible = 1;</code>
   */
  public boolean getEligible() {
    return eligible_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (eligible_ != false) {
      output.writeBool(1, eligible_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (eligible_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, eligible_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof work_leave.LeaveEligibility)) {
      return super.equals(obj);
    }
    work_leave.LeaveEligibility other = (work_leave.LeaveEligibility) obj;

    boolean result = true;
    result = result && (getEligible()
        == other.getEligible());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ELIGIBLE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getEligible());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static work_leave.LeaveEligibility parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static work_leave.LeaveEligibility parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static work_leave.LeaveEligibility parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static work_leave.LeaveEligibility parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static work_leave.LeaveEligibility parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static work_leave.LeaveEligibility parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static work_leave.LeaveEligibility parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static work_leave.LeaveEligibility parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static work_leave.LeaveEligibility parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static work_leave.LeaveEligibility parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(work_leave.LeaveEligibility prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Message Type definition for LeaveEligibility response.
   * </pre>
   *
   * Protobuf type {@code work_leave.LeaveEligibility}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:work_leave.LeaveEligibility)
      work_leave.LeaveEligibilityOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return work_leave.WorkLeaveProto.internal_static_work_leave_LeaveEligibility_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return work_leave.WorkLeaveProto.internal_static_work_leave_LeaveEligibility_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              work_leave.LeaveEligibility.class, work_leave.LeaveEligibility.Builder.class);
    }

    // Construct using work_leave.LeaveEligibility.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      eligible_ = false;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return work_leave.WorkLeaveProto.internal_static_work_leave_LeaveEligibility_descriptor;
    }

    public work_leave.LeaveEligibility getDefaultInstanceForType() {
      return work_leave.LeaveEligibility.getDefaultInstance();
    }

    public work_leave.LeaveEligibility build() {
      work_leave.LeaveEligibility result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public work_leave.LeaveEligibility buildPartial() {
      work_leave.LeaveEligibility result = new work_leave.LeaveEligibility(this);
      result.eligible_ = eligible_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof work_leave.LeaveEligibility) {
        return mergeFrom((work_leave.LeaveEligibility)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(work_leave.LeaveEligibility other) {
      if (other == work_leave.LeaveEligibility.getDefaultInstance()) return this;
      if (other.getEligible() != false) {
        setEligible(other.getEligible());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      work_leave.LeaveEligibility parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (work_leave.LeaveEligibility) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private boolean eligible_ ;
    /**
     * <code>bool eligible = 1;</code>
     */
    public boolean getEligible() {
      return eligible_;
    }
    /**
     * <code>bool eligible = 1;</code>
     */
    public Builder setEligible(boolean value) {
      
      eligible_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool eligible = 1;</code>
     */
    public Builder clearEligible() {
      
      eligible_ = false;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:work_leave.LeaveEligibility)
  }

  // @@protoc_insertion_point(class_scope:work_leave.LeaveEligibility)
  private static final work_leave.LeaveEligibility DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new work_leave.LeaveEligibility();
  }

  public static work_leave.LeaveEligibility getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LeaveEligibility>
      PARSER = new com.google.protobuf.AbstractParser<LeaveEligibility>() {
    public LeaveEligibility parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new LeaveEligibility(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<LeaveEligibility> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<LeaveEligibility> getParserForType() {
    return PARSER;
  }

  public work_leave.LeaveEligibility getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

