// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: work_leave.proto

package work_leave;

public interface LeaveFeedbackOrBuilder extends
    // @@protoc_insertion_point(interface_extends:work_leave.LeaveFeedback)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool granted = 1;</code>
   */
  boolean getGranted();

  /**
   * <code>float accrued_leave_days = 2;</code>
   */
  float getAccruedLeaveDays();

  /**
   * <code>float granted_leave_days = 3;</code>
   */
  float getGrantedLeaveDays();
}
