// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: work_leave.proto

package work_leave;

/**
 * <pre>
 * Message Type definition for LeaveFeedback response.
 * </pre>
 *
 * Protobuf type {@code work_leave.LeaveFeedback}
 */
public  final class LeaveFeedback extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:work_leave.LeaveFeedback)
    LeaveFeedbackOrBuilder {
  // Use LeaveFeedback.newBuilder() to construct.
  private LeaveFeedback(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private LeaveFeedback() {
    granted_ = false;
    accruedLeaveDays_ = 0F;
    grantedLeaveDays_ = 0F;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private LeaveFeedback(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            granted_ = input.readBool();
            break;
          }
          case 21: {

            accruedLeaveDays_ = input.readFloat();
            break;
          }
          case 29: {

            grantedLeaveDays_ = input.readFloat();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return work_leave.WorkLeaveProto.internal_static_work_leave_LeaveFeedback_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return work_leave.WorkLeaveProto.internal_static_work_leave_LeaveFeedback_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            work_leave.LeaveFeedback.class, work_leave.LeaveFeedback.Builder.class);
  }

  public static final int GRANTED_FIELD_NUMBER = 1;
  private boolean granted_;
  /**
   * <code>bool granted = 1;</code>
   */
  public boolean getGranted() {
    return granted_;
  }

  public static final int ACCRUED_LEAVE_DAYS_FIELD_NUMBER = 2;
  private float accruedLeaveDays_;
  /**
   * <code>float accrued_leave_days = 2;</code>
   */
  public float getAccruedLeaveDays() {
    return accruedLeaveDays_;
  }

  public static final int GRANTED_LEAVE_DAYS_FIELD_NUMBER = 3;
  private float grantedLeaveDays_;
  /**
   * <code>float granted_leave_days = 3;</code>
   */
  public float getGrantedLeaveDays() {
    return grantedLeaveDays_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (granted_ != false) {
      output.writeBool(1, granted_);
    }
    if (accruedLeaveDays_ != 0F) {
      output.writeFloat(2, accruedLeaveDays_);
    }
    if (grantedLeaveDays_ != 0F) {
      output.writeFloat(3, grantedLeaveDays_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (granted_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, granted_);
    }
    if (accruedLeaveDays_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(2, accruedLeaveDays_);
    }
    if (grantedLeaveDays_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(3, grantedLeaveDays_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof work_leave.LeaveFeedback)) {
      return super.equals(obj);
    }
    work_leave.LeaveFeedback other = (work_leave.LeaveFeedback) obj;

    boolean result = true;
    result = result && (getGranted()
        == other.getGranted());
    result = result && (
        java.lang.Float.floatToIntBits(getAccruedLeaveDays())
        == java.lang.Float.floatToIntBits(
            other.getAccruedLeaveDays()));
    result = result && (
        java.lang.Float.floatToIntBits(getGrantedLeaveDays())
        == java.lang.Float.floatToIntBits(
            other.getGrantedLeaveDays()));
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + GRANTED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getGranted());
    hash = (37 * hash) + ACCRUED_LEAVE_DAYS_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getAccruedLeaveDays());
    hash = (37 * hash) + GRANTED_LEAVE_DAYS_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getGrantedLeaveDays());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static work_leave.LeaveFeedback parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static work_leave.LeaveFeedback parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static work_leave.LeaveFeedback parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static work_leave.LeaveFeedback parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static work_leave.LeaveFeedback parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static work_leave.LeaveFeedback parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static work_leave.LeaveFeedback parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static work_leave.LeaveFeedback parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static work_leave.LeaveFeedback parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static work_leave.LeaveFeedback parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(work_leave.LeaveFeedback prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Message Type definition for LeaveFeedback response.
   * </pre>
   *
   * Protobuf type {@code work_leave.LeaveFeedback}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:work_leave.LeaveFeedback)
      work_leave.LeaveFeedbackOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return work_leave.WorkLeaveProto.internal_static_work_leave_LeaveFeedback_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return work_leave.WorkLeaveProto.internal_static_work_leave_LeaveFeedback_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              work_leave.LeaveFeedback.class, work_leave.LeaveFeedback.Builder.class);
    }

    // Construct using work_leave.LeaveFeedback.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      granted_ = false;

      accruedLeaveDays_ = 0F;

      grantedLeaveDays_ = 0F;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return work_leave.WorkLeaveProto.internal_static_work_leave_LeaveFeedback_descriptor;
    }

    public work_leave.LeaveFeedback getDefaultInstanceForType() {
      return work_leave.LeaveFeedback.getDefaultInstance();
    }

    public work_leave.LeaveFeedback build() {
      work_leave.LeaveFeedback result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public work_leave.LeaveFeedback buildPartial() {
      work_leave.LeaveFeedback result = new work_leave.LeaveFeedback(this);
      result.granted_ = granted_;
      result.accruedLeaveDays_ = accruedLeaveDays_;
      result.grantedLeaveDays_ = grantedLeaveDays_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof work_leave.LeaveFeedback) {
        return mergeFrom((work_leave.LeaveFeedback)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(work_leave.LeaveFeedback other) {
      if (other == work_leave.LeaveFeedback.getDefaultInstance()) return this;
      if (other.getGranted() != false) {
        setGranted(other.getGranted());
      }
      if (other.getAccruedLeaveDays() != 0F) {
        setAccruedLeaveDays(other.getAccruedLeaveDays());
      }
      if (other.getGrantedLeaveDays() != 0F) {
        setGrantedLeaveDays(other.getGrantedLeaveDays());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      work_leave.LeaveFeedback parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (work_leave.LeaveFeedback) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private boolean granted_ ;
    /**
     * <code>bool granted = 1;</code>
     */
    public boolean getGranted() {
      return granted_;
    }
    /**
     * <code>bool granted = 1;</code>
     */
    public Builder setGranted(boolean value) {
      
      granted_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool granted = 1;</code>
     */
    public Builder clearGranted() {
      
      granted_ = false;
      onChanged();
      return this;
    }

    private float accruedLeaveDays_ ;
    /**
     * <code>float accrued_leave_days = 2;</code>
     */
    public float getAccruedLeaveDays() {
      return accruedLeaveDays_;
    }
    /**
     * <code>float accrued_leave_days = 2;</code>
     */
    public Builder setAccruedLeaveDays(float value) {
      
      accruedLeaveDays_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float accrued_leave_days = 2;</code>
     */
    public Builder clearAccruedLeaveDays() {
      
      accruedLeaveDays_ = 0F;
      onChanged();
      return this;
    }

    private float grantedLeaveDays_ ;
    /**
     * <code>float granted_leave_days = 3;</code>
     */
    public float getGrantedLeaveDays() {
      return grantedLeaveDays_;
    }
    /**
     * <code>float granted_leave_days = 3;</code>
     */
    public Builder setGrantedLeaveDays(float value) {
      
      grantedLeaveDays_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float granted_leave_days = 3;</code>
     */
    public Builder clearGrantedLeaveDays() {
      
      grantedLeaveDays_ = 0F;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:work_leave.LeaveFeedback)
  }

  // @@protoc_insertion_point(class_scope:work_leave.LeaveFeedback)
  private static final work_leave.LeaveFeedback DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new work_leave.LeaveFeedback();
  }

  public static work_leave.LeaveFeedback getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LeaveFeedback>
      PARSER = new com.google.protobuf.AbstractParser<LeaveFeedback>() {
    public LeaveFeedback parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new LeaveFeedback(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<LeaveFeedback> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<LeaveFeedback> getParserForType() {
    return PARSER;
  }

  public work_leave.LeaveFeedback getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

