// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: work_leave.proto

package work_leave;

public interface LeaveEligibilityOrBuilder extends
    // @@protoc_insertion_point(interface_extends:work_leave.LeaveEligibility)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool eligible = 1;</code>
   */
  boolean getEligible();
}
