// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: work_leave.proto

package work_leave;

public final class WorkLeaveProto {
  private WorkLeaveProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_work_leave_Employee_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_work_leave_Employee_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_work_leave_LeaveEligibility_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_work_leave_LeaveEligibility_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_work_leave_LeaveFeedback_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_work_leave_LeaveFeedback_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020work_leave.proto\022\nwork_leave\"g\n\010Employ" +
      "ee\022\023\n\013employee_id\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022\032\n" +
      "\022accrued_leave_days\030\003 \001(\002\022\034\n\024requested_l" +
      "eave_days\030\004 \001(\002\"$\n\020LeaveEligibility\022\020\n\010e" +
      "ligible\030\001 \001(\010\"X\n\rLeaveFeedback\022\017\n\007grante" +
      "d\030\001 \001(\010\022\032\n\022accrued_leave_days\030\002 \001(\002\022\032\n\022g" +
      "ranted_leave_days\030\003 \001(\0022\241\001\n\030EmployeeLeav" +
      "eDaysService\022F\n\020EligibleForLeave\022\024.work_" +
      "leave.Employee\032\034.work_leave.LeaveEligibi" +
      "lity\022=\n\ngrantLeave\022\024.work_leave.Employee",
      "\032\031.work_leave.LeaveFeedbackB\022B\016WorkLeave" +
      "ProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_work_leave_Employee_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_work_leave_Employee_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_work_leave_Employee_descriptor,
        new java.lang.String[] { "EmployeeId", "Name", "AccruedLeaveDays", "RequestedLeaveDays", });
    internal_static_work_leave_LeaveEligibility_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_work_leave_LeaveEligibility_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_work_leave_LeaveEligibility_descriptor,
        new java.lang.String[] { "Eligible", });
    internal_static_work_leave_LeaveFeedback_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_work_leave_LeaveFeedback_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_work_leave_LeaveFeedback_descriptor,
        new java.lang.String[] { "Granted", "AccruedLeaveDays", "GrantedLeaveDays", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
